server:
  port: 8089
spring:
  activemq:
    broker-url: tcp://192.168.0.35:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  freemarker:
    enabled: true
    cache: true
    charset: UTF-8
    suffix: .ftl
mybatis:
  config-location: classpath:mybatis-config.xml
sample:
  activemq:
    host: 192.168.0.35
    port: 61613
    stomp-port: 61614
    user: admin
    passcode: admin
    topic-prefix: real.time.group
    queue-prefix: real.time.point
  juniter:
    email: juniterr@outlook.com